apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: ecommerce
type: Opaque
stringData:
  CUSTOMER_DB: "Host=customers-db;Port=5432;Database=customers_db;Username=postgres;Password=postgres123"
  PRODUCT_DB:  "Host=products-db;Port=5432;Database=products_db;Username=postgres;Password=postgres123"
  ORDER_DB:    "Host=orders-db;Port=5432;Database=orders_db;Username=postgres;Password=postgres123"
  NOTIF_DB:    "Host=notifications-db;Port=5432;Database=notifications_db;Username=postgres;Password=postgres123"
  RABBITMQ_PASSWORD: "rabbit123"
